### ISSUE TITLE
ImportBundleApplicationStartPanel needs also a default locale

### ISSUE THREAD

**Issue by helena95** [astrapi69/bundle-app-ui#3]
The ImportBundleApplicationStartPanel needs also a default locale. For the implementation you can take the [PropertiesDirectoryWalker](https://github.com/astrapi69/resourcebundle-core/blob/develop/resourcebundle-inspector/src/main/java/de/alpharogroup/resourcebundle/inspector/search/PropertiesDirectoryWalker.java).

**Comment by astrapi69** [comment]
default locale added to ImportBundleApplicationStartPanel
