### ISSUE TITLE
create an export process from a bundle-application or resource-bundles

### ISSUE THREAD

**Issue by jimmyMaci** [astrapi69/bundle-app-ui#8]
For now there is an import process to import an single file of resource-bundles or even a bundle-application.
It would be nice to give the user the opportunity to export resource-bundles or even a bundle-application. Insert therefor a button 'export' to the panels.

**Comment by astrapi69** [comment]
Hi @jimmyMaci, i have insert now this functionality. You can make a pull and check it out. I will close this issue
